/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.app;

import game.list.LinkedList;

import static game.app.MessageUtils.getMessage;
import static game.utilities.StringUtils.join;
import static game.utilities.StringUtils.split;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
