package GetPriceLabel;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getPriceLable(String itemName, Double price) {
        return String.format("The price for item: %s is %.2f", itemName, price);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
