package GetPriceLabel;

import static org.junit.Assert.assertNotNull;

import org.junit.Assert;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

public class AppTest {

    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testGetCoffeeMachinePrice() {
        App classUnderTest = new App();
        String result = classUnderTest.getPriceLable("Coffee Machine", 15.99);
        Assert.assertEquals(String.valueOf("The price for item: Coffee Machine is 15.99"), result);
    }

}
